# Generated by Django 4.2.16 on 2026-06-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('icone', models.CharField(blank=True, default='💼', max_length=10, verbose_name='Icône')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (MAD)')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/', verbose_name='Justificatif (facture/reçu)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='agencies.agency', verbose_name='Agence')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.categoriedepense', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
