# Generated by Django 4.2.16 on 2026-06-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('categorie', models.CharField(choices=[('economique', 'Économique'), ('normale', 'Normale'), ('luxe', 'Luxe')], max_length=20, verbose_name='Catégorie')),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20, verbose_name='Transmission')),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], default='diesel', max_length=20, verbose_name='Carburant')),
                ('nombre_places', models.PositiveSmallIntegerField(default=5, verbose_name='Nombre de places')),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour (MAD)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Photo principale')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='agencies.agency', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['categorie', 'marque', 'modele'],
            },
        ),
    ]
