# Generated by Django 4.2.16 on 2026-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'agence")),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('couleur_principale', models.CharField(default='#C8A96E', help_text='Ex: #C8A96E', max_length=7, verbose_name='Couleur principale (hex)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
            },
        ),
    ]
