# Generated by Django 4.2.16 on 2026-06-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_revision', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('courroie', 'Courroie de distribution'), ('climatisation', 'Climatisation'), ('autre', 'Autre')], max_length=30, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description des travaux')),
                ('km_compteur', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (MAD)')),
                ('garage', models.CharField(blank=True, max_length=200, verbose_name='Garage / Prestataire')),
                ('prochaine_revision_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prochaine révision (km)')),
                ('prochaine_revision_date', models.DateField(blank=True, null=True, verbose_name='Prochaine révision (date)')),
                ('facture', models.FileField(blank=True, null=True, upload_to='revisions/', verbose_name='Facture')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Révision / Entretien',
                'verbose_name_plural': 'Révisions / Entretiens',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PleinCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('km_compteur', models.PositiveIntegerField(verbose_name='Kilométrage au compteur')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Litres')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant (MAD)')),
                ('type_carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique')], default='diesel', max_length=20, verbose_name='Carburant')),
                ('station', models.CharField(blank=True, max_length=200, verbose_name='Station-service')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pleins', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Plein carburant',
                'verbose_name_plural': 'Pleins carburant',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Lavage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_lavage', models.CharField(choices=[('exterieur', 'Extérieur'), ('interieur', 'Intérieur'), ('complet', 'Complet'), ('detailing', 'Détailing')], default='complet', max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant (MAD)')),
                ('prestataire', models.CharField(blank=True, max_length=200, verbose_name='Prestataire / Station')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavages', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Lavage',
                'verbose_name_plural': 'Lavages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(max_length=200, verbose_name="Compagnie d'assurance")),
                ('numero_police', models.CharField(blank=True, max_length=100, verbose_name='Numéro de police')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name="Date d'expiration")),
                ('montant_annuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant annuel (MAD)')),
                ('document', models.FileField(blank=True, null=True, upload_to='assurances/', verbose_name='Document (PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant (MAD)')),
                ('recu', models.FileField(blank=True, null=True, upload_to='vignettes/', verbose_name='Reçu (PDF/photo)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Vignette',
                'verbose_name_plural': 'Vignettes',
                'ordering': ['-annee'],
                'unique_together': {('car', 'annee')},
            },
        ),
    ]
