# Generated by Django 4.2.16 on 2026-06-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('telephone_client', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_client', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('notes_agence', models.TextField(blank=True, verbose_name='Notes internes')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('raison', models.CharField(help_text='Ex: Maintenance, Révision, Réservé agence', max_length=300, verbose_name='Raison')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Période bloquée',
                'verbose_name_plural': 'Périodes bloquées',
                'ordering': ['date_debut'],
            },
        ),
    ]
